name: Compliance
on:
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18, 20]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install -g pnpm
            - run: pnpm install
            - run: pnpm lint

    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18, 20]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install -g pnpm
            - run: pnpm install
            - run: pnpm build

    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18, 20]
                redis-version: [6, 7]

        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Start Redis
              uses: supercharge/redis-github-action@1.8.0
              with:
                  redis-version: ${{ matrix.redis-version }}

            - run: npm install -g pnpm
            - run: pnpm install
            - run: pnpm build
            - run: pnpm test
